<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>forio</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Forio Model</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|FOREACH|ARRAYAVG,ARRAYSTDDEV)\b</string>
			<key>name</key>
			<string>keyword.control.forio</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.forio</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(##).*$\n?</string>
			<key>name</key>
			<string>comment.line.forio</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.definition</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(M) .+$\n?</string>
			<key>name</key>
			<string>constant.model.forio</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.definition</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(V) .+$\n?</string>
			<key>name</key>
			<string>variable.variable.forio</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.definition</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.variable.forio</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.property.forio</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(P) (.+)\.(.+)$\n?</string>
			<key>name</key>
			<string>entity.property.forio</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.forio</string>
	<key>uuid</key>
	<string>D70594AA-BD0A-4BC8-9814-3E1A544BF4A6</string>
</dict>
</plist>
