<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eqn</string>
		<string>forio</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Forio Model</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(##).*$\n?</string>
			<key>name</key>
			<string>comment.line.forio</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(M) ([A-Za-z]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.forio</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.model.settings.forio</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>expression.model.forio</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stdfunction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bools</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(D|V|R)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.forio</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.forio</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>expression.variable.forio</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stdfunction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bools</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#grouping</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(P)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.forio</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>expression.property.forio</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stdfunction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bools</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#grouping</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#stdfunction</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#grouping</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bools</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bools</key>
		<dict>
			<key>match</key>
			<string>true|false|FALSE|TRUE</string>
			<key>name</key>
			<string>support.bools.forio</string>
		</dict>
		<key>grouping</key>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>string.grouping.forio</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>=|&gt;|&lt;|\*|\+|\/|-|&amp;|\|\%|\.\.</string>
			<key>name</key>
			<string>keyword.operator.forio</string>
		</dict>
		<key>property</key>
		<dict>
			<key>begin</key>
			<string>(\.)[A-Za-z]</string>
			<key>end</key>
			<string>\b</string>
			<key>name</key>
			<string>support.property.forio</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<key>stdfunction</key>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|FOREACH|ARRAYAVG|ARRAYSTDDEV|ARRAYSUM|SAFEDIV0|MAX|MIN|IF|SMOOTH|ARRAYGRAPH|LOOKUP|INITIAL|ROUND|PREVIOUS|STEP|true|false|TRUE|FALSE|NAN)\b</string>
			<key>name</key>
			<string>support.function.forio</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z]\w*( \w+)*</string>
			<key>name</key>
			<string>variable.userdefined.forio</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.forio</string>
	<key>uuid</key>
	<string>D70594AA-BD0A-4BC8-9814-3E1A544BF4A6</string>
</dict>
</plist>
